### ISSUE TITLE
Blacklist For Unchained 

### ISSUE THREAD

**Issue by RiftSpatial** [timinc-cobble/cobblemon-unchained-1.4-fabric#7]
Incorporate a blacklist for Unchained using either labels like tags, or specific name of the Pokemon, or both. Perhaps even a whitelist that overrides this blacklist, say you have legendaries blacklisted, but you want a certain legendary to be whitelisted, without having to list each individual legendary, you would put it in that whitelist.

**Comment by tmetcalfe89** [comment]
> say you have legendaries blacklisted, but you want a certain legendary to be whitelisted, without having to list each individual legendary, you would put it in that whitelist.

If you have just a whitelist or a blacklist, they operate independently. If you have both, the whitelist becomes a list of exceptions to the blacklist.

**Comment by tmetcalfe89** [comment]
Fixed by #17
